version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 32
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  influxdb:
    image: brandpulse-influxdb:latest
    ports:
      - "8086:8086"
  producer:
    image: brandpulse-producer:latest
    depends_on:
      - kafka
  consumer:
    image: brandpulse-consumer:latest
    depends_on:
      - kafka
      - influxdb
  dashboard:
    image: brandpulse-dashboard:latest
    depends_on:
      - influxdb
    ports:
      - "3000:3000"